### ISSUE TITLE
I cannot load SEND_PICTURES from within my OobaBooga instance after changing in settings to restarting. Worked earlier today.

### ISSUE THREAD

**Issue by cleverestx** [oobabooga/text-generation-webui-extensions#20]
I get this error. I do not know why. I cannot load SEND_PICTURES or LLAVA and I've tried replacing the script.py in each of their exertions folders with the ones from the website, but this does fix it. What else can I do?

![image](https://github.com/oobabooga/text-generation-webui-extensions/assets/28905253/aecca36c-c419-4f5d-9864-8462def2493f)

I'm using OobaBooga's Windows (latest version)

**Comment by cleverestx** [comment]
Did I submit this in the wrong place? I hope not...

**Comment by oobabooga** [comment]
Wrong repository, this is just a list of user-contributed extensions.
