### ISSUE TITLE
Could someone please add piperTTS as an extension?

### ISSUE THREAD

**Issue by FemBoxbrawl** [oobabooga/text-generation-webui-extensions#58]
PiperTTS is one if not the fastest AI tts I know ,and was wondering if someome could add it to textgenwebUI, because if you train a custom voice model , you can make it sound accurate. but really what i like the most is the speed of it.

**Comment by Martin-Laclaustra** [comment]
Please add https://github.com/tijo95/piper_tts to the list of available extensions.

**Comment by Martin-Laclaustra** [comment]
This issue can be closed now that the extension has been added to the list.
