### ISSUE TITLE
Autobooga not developed anymore by maintainer

### ISSUE THREAD

**Issue by dragos240** [oobabooga/text-generation-webui-extensions#59]
From the [README](https://github.com/sammyf/Autobooga/blob/master/README.md):
> THIS EXTENSION IS NOT SUPPORTED ANYMORE

Might be good to remove it

**Comment by oobabooga** [comment]
Thanks @dragos240 

https://github.com/oobabooga/text-generation-webui-extensions/commit/72c90b494753ae4bcbea34d27149bfa29c889751
