### ISSUE TITLE
AttributeError: module 'gradio.components' has no attribute '__all__'

### ISSUE THREAD

**Issue by whyttt6** [oobabooga/text-generation-webui-extensions#79]
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\whytt\pinokio\api\oobabooga.pinokio.git\text-generation-webui\server.py:21 in <module>                      │
│                                                                                                                      │
│    20 with RequestBlocker():                                                                                         │
│ ❱  21     from modules import gradio_hijack                                                                          │
│    22     import gradio as gr                                                                                        │
│                                                                                                                      │
│ C:\Users\whytt\pinokio\api\oobabooga.pinokio.git\text-generation-webui\modules\gradio_hijack.py:52 in <module>       │
│                                                                                                                      │
│   51                                                                                                                 │
│ ❱ 52 for component in set(gr.components.__all__ + gr.layouts.__all__):                                               │
│   53     repair(getattr(gr, component, None))                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'gradio.components' has no attribute '__all__'

**Comment by Miamas777** [comment]
up，i have the same too

**Comment by Miamas777** [comment]
i solve the problem by upgrading gradio to 4.26.0`pip install gradio==4.26.0`
